on:
  push:
    branches:
      - master
    tags:
      - "v*"

name: GitHub Release

jobs:
  release:
    name: Release and Upload Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: git fetch --all --tags

      - name: Check version change
        uses: thebongy/version-check@v1
        id: check
        with:
          file: package.json
          failBuild: false
          tagFormat: v${version}


      - name: Echo variables
        run: |
          echo "versionChanged- ${{steps.check.outputs.versionChanged}}"
          echo "releaseVersion- ${{steps.check.outputs.releaseVersion}}"
      
      - name: Create image file
        if: steps.check.outputs.versionChanged == 'true'
        run: |
          sudo apt-get install genisoimage
          genisoimage -output seed.img -volid cidata -joliet -rock user-data meta-data

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: steps.check.outputs.versionChanged == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check.outputs.releaseVersion }}
          release_name: Release ${{ steps.check.outputs.releaseVersion }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        if: steps.check.outputs.versionChanged == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./seed.img
          asset_name: seed.img
          asset_content_type: application/unknown
